//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_with_online_orders.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comanda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comanda()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int id { get; set; }
        public int id_utilizator { get; set; }
        public int id_stare_comanda { get; set; }
        public double pret { get; set; }
        public Nullable<System.DateTime> data_comanda { get; set; }
        public string cod_comanda { get; set; }
        public Nullable<System.DateTime> ora_livrare { get; set; }
    
        public virtual Cont_utilizator Cont_utilizator { get; set; }
        public virtual Stare_Comanda Stare_Comanda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
