//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_with_online_orders.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont_utilizator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cont_utilizator()
        {
            this.Comandas = new HashSet<Comanda>();
        }
    
        public int idUser { get; set; }
        public string nume { get; set; }
        public string prenume { get; set; }
        public string nr_tel { get; set; }
        public string adresa { get; set; }
        public string email { get; set; }
        public string parola { get; set; }
        public int id_categorie { get; set; }
    
        public virtual Categorie_utilizator Categorie_utilizator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comanda> Comandas { get; set; }
    }
}
