//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_with_online_orders.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preparat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preparat()
        {
            this.Fotografies = new HashSet<Fotografie>();
            this.Items = new HashSet<Item>();
            this.Meniu_Preparat = new HashSet<Meniu_Preparat>();
            this.Preparat_Alergen = new HashSet<Preparat_Alergen>();
        }
    
        public int idPreparat { get; set; }
        public string denumire { get; set; }
        public double pret { get; set; }
        public Nullable<int> cantitate_per_portie { get; set; }
        public Nullable<int> cantitatea_totala { get; set; }
        public int id_categorie { get; set; }
    
        public virtual Categorie_preparat Categorie_preparat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotografie> Fotografies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meniu_Preparat> Meniu_Preparat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preparat_Alergen> Preparat_Alergen { get; set; }
    }
}
